const MUNDIAL_DATA = {
  version: "v3",
  lastUpdate: "2026-06-17",

  partidosOficiales: [
    {"id":"m001","fecha":"2026-06-11","hora":"13:00","utc_offset":"-6","local":"México","visitante":"Sudáfrica","grupo":"A","jornada":1,"sede":"Ciudad de México","resultado":null},
    {"id":"m002","fecha":"2026-06-11","hora":"20:00","utc_offset":"-6","local":"Corea del Sur","visitante":"Chequia","grupo":"A","jornada":1,"sede":"Guadalajara","resultado":null},
    {"id":"m003","fecha":"2026-06-18","hora":"12:00","utc_offset":"-4","local":"Chequia","visitante":"Sudáfrica","grupo":"A","jornada":8,"sede":"Atlanta","resultado":null},
    {"id":"m004","fecha":"2026-06-18","hora":"19:00","utc_offset":"-6","local":"México","visitante":"Corea del Sur","grupo":"A","jornada":8,"sede":"Guadalajara","resultado":null},
    {"id":"m005","fecha":"2026-06-24","hora":"19:00","utc_offset":"-6","local":"Chequia","visitante":"México","grupo":"A","jornada":14,"sede":"Ciudad de México","resultado":null},
    {"id":"m006","fecha":"2026-06-24","hora":"19:00","utc_offset":"-6","local":"Sudáfrica","visitante":"Corea del Sur","grupo":"A","jornada":14,"sede":"Monterrey","resultado":null},
    {"id":"m007","fecha":"2026-06-12","hora":"15:00","utc_offset":"-4","local":"Canadá","visitante":"Bosnia y Herzegovina","grupo":"B","jornada":2,"sede":"Toronto","resultado":null},
    {"id":"m008","fecha":"2026-06-13","hora":"12:00","utc_offset":"-7","local":"Catar","visitante":"Suiza","grupo":"B","jornada":3,"sede":"San Francisco (Santa Clara)","resultado":null},
    {"id":"m009","fecha":"2026-06-18","hora":"12:00","utc_offset":"-7","local":"Suiza","visitante":"Bosnia y Herzegovina","grupo":"B","jornada":8,"sede":"Los Ángeles (Inglewood)","resultado":null},
    {"id":"m010","fecha":"2026-06-18","hora":"15:00","utc_offset":"-7","local":"Canadá","visitante":"Catar","grupo":"B","jornada":8,"sede":"Vancouver","resultado":null},
    {"id":"m011","fecha":"2026-06-24","hora":"12:00","utc_offset":"-7","local":"Suiza","visitante":"Canadá","grupo":"B","jornada":14,"sede":"Vancouver","resultado":null},
    {"id":"m012","fecha":"2026-06-24","hora":"12:00","utc_offset":"-7","local":"Bosnia y Herzegovina","visitante":"Catar","grupo":"B","jornada":14,"sede":"Seattle","resultado":null},
    {"id":"m013","fecha":"2026-06-13","hora":"18:00","utc_offset":"-4","local":"Brasil","visitante":"Marruecos","grupo":"C","jornada":3,"sede":"Nueva York/Nueva Jersey","resultado":null},
    {"id":"m014","fecha":"2026-06-13","hora":"21:00","utc_offset":"-4","local":"Haití","visitante":"Escocia","grupo":"C","jornada":3,"sede":"Boston (Foxborough)","resultado":null},
    {"id":"m015","fecha":"2026-06-19","hora":"18:00","utc_offset":"-4","local":"Escocia","visitante":"Marruecos","grupo":"C","jornada":9,"sede":"Boston (Foxborough)","resultado":null},
    {"id":"m016","fecha":"2026-06-19","hora":"20:30","utc_offset":"-4","local":"Brasil","visitante":"Haití","grupo":"C","jornada":9,"sede":"Filadelfia","resultado":null},
    {"id":"m017","fecha":"2026-06-24","hora":"18:00","utc_offset":"-4","local":"Escocia","visitante":"Brasil","grupo":"C","jornada":14,"sede":"Miami (Miami Gardens)","resultado":null},
    {"id":"m018","fecha":"2026-06-24","hora":"18:00","utc_offset":"-4","local":"Marruecos","visitante":"Haití","grupo":"C","jornada":14,"sede":"Atlanta","resultado":null},
    {"id":"m019","fecha":"2026-06-12","hora":"18:00","utc_offset":"-7","local":"Estados Unidos","visitante":"Paraguay","grupo":"D","jornada":2,"sede":"Los Ángeles (Inglewood)","resultado":null},
    {"id":"m020","fecha":"2026-06-13","hora":"21:00","utc_offset":"-7","local":"Australia","visitante":"Turquía","grupo":"D","jornada":3,"sede":"Vancouver","resultado":null},
    {"id":"m021","fecha":"2026-06-19","hora":"12:00","utc_offset":"-7","local":"Estados Unidos","visitante":"Australia","grupo":"D","jornada":9,"sede":"Seattle","resultado":null},
    {"id":"m022","fecha":"2026-06-19","hora":"20:00","utc_offset":"-7","local":"Turquía","visitante":"Paraguay","grupo":"D","jornada":9,"sede":"San Francisco (Santa Clara)","resultado":null},
    {"id":"m023","fecha":"2026-06-25","hora":"19:00","utc_offset":"-7","local":"Turquía","visitante":"Estados Unidos","grupo":"D","jornada":15,"sede":"Los Ángeles (Inglewood)","resultado":null},
    {"id":"m024","fecha":"2026-06-25","hora":"19:00","utc_offset":"-7","local":"Paraguay","visitante":"Australia","grupo":"D","jornada":15,"sede":"San Francisco (Santa Clara)","resultado":null},
    {"id":"m025","fecha":"2026-06-14","hora":"12:00","utc_offset":"-5","local":"Alemania","visitante":"Curazao","grupo":"E","jornada":4,"sede":"Houston","resultado":null},
    {"id":"m026","fecha":"2026-06-14","hora":"19:00","utc_offset":"-4","local":"Costa de Marfil","visitante":"Ecuador","grupo":"E","jornada":4,"sede":"Filadelfia","resultado":null},
    {"id":"m027","fecha":"2026-06-20","hora":"16:00","utc_offset":"-4","local":"Alemania","visitante":"Costa de Marfil","grupo":"E","jornada":10,"sede":"Toronto","resultado":null},
    {"id":"m028","fecha":"2026-06-20","hora":"19:00","utc_offset":"-5","local":"Ecuador","visitante":"Curazao","grupo":"E","jornada":10,"sede":"Kansas City","resultado":null},
    {"id":"m029","fecha":"2026-06-25","hora":"16:00","utc_offset":"-4","local":"Curazao","visitante":"Costa de Marfil","grupo":"E","jornada":15,"sede":"Filadelfia","resultado":null},
    {"id":"m030","fecha":"2026-06-25","hora":"16:00","utc_offset":"-4","local":"Ecuador","visitante":"Alemania","grupo":"E","jornada":15,"sede":"Nueva York/Nueva Jersey","resultado":null},
    {"id":"m031","fecha":"2026-06-14","hora":"15:00","utc_offset":"-5","local":"Países Bajos","visitante":"Japón","grupo":"F","jornada":4,"sede":"Dallas (Arlington)","resultado":null},
    {"id":"m032","fecha":"2026-06-14","hora":"20:00","utc_offset":"-6","local":"Suecia","visitante":"Túnez","grupo":"F","jornada":4,"sede":"Monterrey","resultado":null},
    {"id":"m033","fecha":"2026-06-20","hora":"12:00","utc_offset":"-5","local":"Países Bajos","visitante":"Suecia","grupo":"F","jornada":10,"sede":"Houston","resultado":null},
    {"id":"m034","fecha":"2026-06-20","hora":"22:00","utc_offset":"-6","local":"Túnez","visitante":"Japón","grupo":"F","jornada":10,"sede":"Monterrey","resultado":null},
    {"id":"m035","fecha":"2026-06-25","hora":"18:00","utc_offset":"-5","local":"Japón","visitante":"Suecia","grupo":"F","jornada":15,"sede":"Dallas (Arlington)","resultado":null},
    {"id":"m036","fecha":"2026-06-25","hora":"18:00","utc_offset":"-5","local":"Túnez","visitante":"Países Bajos","grupo":"F","jornada":15,"sede":"Kansas City","resultado":null},
    {"id":"m037","fecha":"2026-06-15","hora":"12:00","utc_offset":"-7","local":"Bélgica","visitante":"Egipto","grupo":"G","jornada":5,"sede":"Seattle","resultado":null},
    {"id":"m038","fecha":"2026-06-15","hora":"18:00","utc_offset":"-7","local":"Irán","visitante":"Nueva Zelanda","grupo":"G","jornada":5,"sede":"Los Ángeles (Inglewood)","resultado":null},
    {"id":"m039","fecha":"2026-06-21","hora":"12:00","utc_offset":"-7","local":"Bélgica","visitante":"Irán","grupo":"G","jornada":11,"sede":"Los Ángeles (Inglewood)","resultado":null},
    {"id":"m040","fecha":"2026-06-21","hora":"18:00","utc_offset":"-7","local":"Nueva Zelanda","visitante":"Egipto","grupo":"G","jornada":11,"sede":"Vancouver","resultado":null},
    {"id":"m041","fecha":"2026-06-26","hora":"20:00","utc_offset":"-7","local":"Egipto","visitante":"Irán","grupo":"G","jornada":16,"sede":"Seattle","resultado":null},
    {"id":"m042","fecha":"2026-06-26","hora":"20:00","utc_offset":"-7","local":"Nueva Zelanda","visitante":"Bélgica","grupo":"G","jornada":16,"sede":"Vancouver","resultado":null},
    {"id":"m043","fecha":"2026-06-15","hora":"12:00","utc_offset":"-4","local":"España","visitante":"Cabo Verde","grupo":"H","jornada":5,"sede":"Atlanta","resultado":null},
    {"id":"m044","fecha":"2026-06-15","hora":"18:00","utc_offset":"-4","local":"Arabia Saudita","visitante":"Uruguay","grupo":"H","jornada":5,"sede":"Miami (Miami Gardens)","resultado":null},
    {"id":"m045","fecha":"2026-06-21","hora":"12:00","utc_offset":"-4","local":"España","visitante":"Arabia Saudita","grupo":"H","jornada":11,"sede":"Atlanta","resultado":null},
    {"id":"m046","fecha":"2026-06-21","hora":"18:00","utc_offset":"-4","local":"Uruguay","visitante":"Cabo Verde","grupo":"H","jornada":11,"sede":"Miami (Miami Gardens)","resultado":null},
    {"id":"m047","fecha":"2026-06-26","hora":"19:00","utc_offset":"-5","local":"Cabo Verde","visitante":"Arabia Saudita","grupo":"H","jornada":16,"sede":"Houston","resultado":null},
    {"id":"m048","fecha":"2026-06-26","hora":"18:00","utc_offset":"-6","local":"Uruguay","visitante":"España","grupo":"H","jornada":16,"sede":"Guadalajara","resultado":null},
    {"id":"m049","fecha":"2026-06-16","hora":"15:00","utc_offset":"-4","local":"Francia","visitante":"Senegal","grupo":"I","jornada":6,"sede":"Nueva York/Nueva Jersey","resultado":null},
    {"id":"m050","fecha":"2026-06-16","hora":"18:00","utc_offset":"-4","local":"Irak","visitante":"Noruega","grupo":"I","jornada":6,"sede":"Boston (Foxborough)","resultado":null},
    {"id":"m051","fecha":"2026-06-22","hora":"17:00","utc_offset":"-4","local":"Francia","visitante":"Irak","grupo":"I","jornada":12,"sede":"Filadelfia","resultado":null},
    {"id":"m052","fecha":"2026-06-22","hora":"20:00","utc_offset":"-4","local":"Noruega","visitante":"Senegal","grupo":"I","jornada":12,"sede":"Nueva York/Nueva Jersey","resultado":null},
    {"id":"m053","fecha":"2026-06-26","hora":"15:00","utc_offset":"-4","local":"Noruega","visitante":"Francia","grupo":"I","jornada":16,"sede":"Boston (Foxborough)","resultado":null},
    {"id":"m054","fecha":"2026-06-26","hora":"15:00","utc_offset":"-4","local":"Senegal","visitante":"Irak","grupo":"I","jornada":16,"sede":"Toronto","resultado":null},
    {"id":"m055","fecha":"2026-06-16","hora":"20:00","utc_offset":"-5","local":"Argentina","visitante":"Argelia","grupo":"J","jornada":6,"sede":"Kansas City","resultado":null},
    {"id":"m056","fecha":"2026-06-16","hora":"21:00","utc_offset":"-7","local":"Austria","visitante":"Jordania","grupo":"J","jornada":6,"sede":"San Francisco (Santa Clara)","resultado":null},
    {"id":"m057","fecha":"2026-06-22","hora":"12:00","utc_offset":"-5","local":"Argentina","visitante":"Austria","grupo":"J","jornada":12,"sede":"Dallas (Arlington)","resultado":null},
    {"id":"m058","fecha":"2026-06-22","hora":"20:00","utc_offset":"-7","local":"Jordania","visitante":"Argelia","grupo":"J","jornada":12,"sede":"San Francisco (Santa Clara)","resultado":null},
    {"id":"m059","fecha":"2026-06-27","hora":"21:00","utc_offset":"-5","local":"Argelia","visitante":"Austria","grupo":"J","jornada":17,"sede":"Kansas City","resultado":null},
    {"id":"m060","fecha":"2026-06-27","hora":"21:00","utc_offset":"-5","local":"Jordania","visitante":"Argentina","grupo":"J","jornada":17,"sede":"Dallas (Arlington)","resultado":null},
    {"id":"m061","fecha":"2026-06-17","hora":"12:00","utc_offset":"-5","local":"Portugal","visitante":"RD Congo","grupo":"K","jornada":7,"sede":"Houston","resultado":null},
    {"id":"m062","fecha":"2026-06-17","hora":"20:00","utc_offset":"-6","local":"Uzbekistán","visitante":"Colombia","grupo":"K","jornada":7,"sede":"Ciudad de México","resultado":null},
    {"id":"m063","fecha":"2026-06-23","hora":"12:00","utc_offset":"-5","local":"Portugal","visitante":"Uzbekistán","grupo":"K","jornada":13,"sede":"Houston","resultado":null},
    {"id":"m064","fecha":"2026-06-23","hora":"20:00","utc_offset":"-6","local":"Colombia","visitante":"RD Congo","grupo":"K","jornada":13,"sede":"Guadalajara","resultado":null},
    {"id":"m065","fecha":"2026-06-27","hora":"19:30","utc_offset":"-4","local":"Colombia","visitante":"Portugal","grupo":"K","jornada":17,"sede":"Miami (Miami Gardens)","resultado":null},
    {"id":"m066","fecha":"2026-06-27","hora":"19:30","utc_offset":"-4","local":"RD Congo","visitante":"Uzbekistán","grupo":"K","jornada":17,"sede":"Atlanta","resultado":null},
    {"id":"m067","fecha":"2026-06-17","hora":"15:00","utc_offset":"-5","local":"Inglaterra","visitante":"Croacia","grupo":"L","jornada":7,"sede":"Dallas (Arlington)","resultado":null},
    {"id":"m068","fecha":"2026-06-17","hora":"19:00","utc_offset":"-4","local":"Ghana","visitante":"Panamá","grupo":"L","jornada":7,"sede":"Toronto","resultado":null},
    {"id":"m069","fecha":"2026-06-23","hora":"16:00","utc_offset":"-4","local":"Inglaterra","visitante":"Ghana","grupo":"L","jornada":13,"sede":"Boston (Foxborough)","resultado":null},
    {"id":"m070","fecha":"2026-06-23","hora":"19:00","utc_offset":"-4","local":"Panamá","visitante":"Croacia","grupo":"L","jornada":13,"sede":"Toronto","resultado":null},
    {"id":"m071","fecha":"2026-06-27","hora":"17:00","utc_offset":"-4","local":"Panamá","visitante":"Inglaterra","grupo":"L","jornada":17,"sede":"Nueva York/Nueva Jersey","resultado":null},
    {"id":"m072","fecha":"2026-06-27","hora":"17:00","utc_offset":"-4","local":"Croacia","visitante":"Ghana","grupo":"L","jornada":17,"sede":"Filadelfia","resultado":null}
  ],

  grupos: {
    A: ["México", "Sudáfrica", "Corea del Sur", "Chequia"],
    B: ["Canadá", "Bosnia y Herzegovina", "Catar", "Suiza"],
    C: ["Brasil", "Marruecos", "Haití", "Escocia"],
    D: ["Estados Unidos", "Paraguay", "Australia", "Turquía"],
    E: ["Alemania", "Curazao", "Costa de Marfil", "Ecuador"],
    F: ["Países Bajos", "Japón", "Suecia", "Túnez"],
    G: ["Bélgica", "Egipto", "Irán", "Nueva Zelanda"],
    H: ["España", "Cabo Verde", "Arabia Saudita", "Uruguay"],
    I: ["Francia", "Senegal", "Irak", "Noruega"],
    J: ["Argentina", "Argelia", "Austria", "Jordania"],
    K: ["Portugal", "RD Congo", "Uzbekistán", "Colombia"],
    L: ["Inglaterra", "Croacia", "Ghana", "Panamá"]
  },

  picks: [],
  combinadas: []
};
